### ISSUE TITLE
云编译dnsmasq-full报错，请求指点迷津呀！

### ISSUE THREAD

**Issue by kaixin009** [HandsomeMod/HandsomeMod#10]
Configuring libipset13.
Configuring ipset.
Configuring iptables.
Configuring iptables-mod-tproxy.
Configuring microsocks.
Configuring tcping.
Configuring libnghttp2-14.
Configuring libcurl4.
Configuring curl.
Collected errors:
 * check_data_file_clashes: Package dnsmasq wants to install file /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq-full
Configuring xray-core.
 * check_data_file_clashes: Package dnsmasq wants to install file /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq-full
Configuring shadowsocksr-libev-ssr-local.
Configuring shadowsocksr-libev-ssr-redir.
Configuring simple-obfs-client.
Configuring luci-app-ssr-plus.
Configuring odhcp6c.
Configuring docker.
Configuring uci.
Configuring ip6tables.
Configuring kmod-ipt-nat6.
Configuring odhcpd-ipv6only.
Configuring ipv6helper.
Configuring kmod-input-evdev.
Configuring dropbear.
Configuring kmod-crypto-kpp.
Configuring kmod-crypto-ecdh.
Configuring mtd.
Configuring kmod-crypto-ecb.
Configuring kmod-hid.
Configuring kmod-crypto-cmac.
Configuring kmod-regmap-core.
Configuring kmod-bluetooth.
Configuring kmod-qcom-bluetooth.
Configuring frpc.
Configuring eudev.
Configuring qrtr-ns.
Configuring rmtfs.
Configuring libconfig11.
Configuring libusbgx.
Configuring android-tools-adbd.
Configuring gc.
Configuring mount-utils.
Configuring rootfs-resizer.
Configuring openstick-tweaks.
Configuring luci-app-frpc.
Configuring urandom-seed.
Configuring logd.
Configuring qcom-msm8916-modem-openstick-ufi001c-firmware.
Configuring luci-app-ddnsto.
Configuring wireless-regdb.
Configuring kmod-cfg80211.
Configuring kmod-mac80211.
Configuring kmod-wcn36xx.
Configuring qcom-msm8916-openstick-ufi001c-wcnss-firmware.
Configuring libfdisk1.
Configuring libncurses6.
Configuring rpmsgexport.
Configuring qcom-msm8916-wcnss-openstick-ufi001c-nv.
Configuring fdisk.
Configuring luci-lib-fs.
Configuring luci-app-filetransfer.
Configuring kmod-qcom-modem.
Configuring luci-app-docker.
Configuring kmod-ipt-offload.
Configuring urngd.
Configuring ppp-mod-pppoe.
make[2]: Leaving directory '/workdir/openwrt'
 * check_data_file_clashes: Package dnsmasq wants to install file /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/etc/uci-defaults/50-dnsmasq-migrate-resolv-conf-auto.sh
	But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/usr/share/acl.d/dnsmasq_acl.json
	But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/usr/share/dnsmasq/dhcpbogushostname.conf
	But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq-full
 * opkg_install_cmd: Cannot install package dnsmasq.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[1]: *** [package/Makefile:111: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53+neon_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by AK201314** [comment]
[log.txt](https://github.com/HandsomeMod/HandsomeMod/files/9227518/log.txt)

大佬去掉dnsmasq还报错呢！！！

Enabling wpad
sed -i "s/Installed-Time: .*/Installed-Time: 1659098230/" /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/usr/lib/opkg/status
rm -rf /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/boot /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/tmp/* /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/usr/lib/opkg/info/*.postinst* /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/usr/lib/opkg/lists/* /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/var/lock/*.lock
find /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/ -mindepth 1 -execdir touch -hcd "@1659098230" "{}" +
make[2]: Leaving directory '/workdir/openwrt'
make[2]: Entering directory '/workdir/openwrt'
make[3]: Entering directory '/workdir/openwrt/target/linux'
make[4]: Entering directory '/workdir/openwrt/target/linux/msm89xx'
rm -f /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/localversion
/workdir/openwrt/scripts/kconfig.pl  + /workdir/openwrt/target/linux/generic/config-5.10 /workdir/openwrt/target/linux/msm89xx/config-5.10 > /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /workdir/openwrt/.config >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.target
/workdir/openwrt/scripts/package-metadata.pl kconfig /workdir/openwrt/tmp/.packageinfo /workdir/openwrt/.config 5.10 > /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.override
/workdir/openwrt/scripts/kconfig.pl 'm+' '+' /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.target /dev/null /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.override > /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.set
mv /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.set /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.old
grep -v INITRAMFS /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.old > /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.set
rm -rf /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/modules
cmp -s /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.set /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.prev || { cp /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.set /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config; cp /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.set /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.prev; }
export MAKEFLAGS= ; [ -d /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/user_headers ] || make -C /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl=target-aarch64_cortex-a53+neon_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Fri Jul 29 12:37:10 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/workdir/openwrt/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.33 CC="aarch64-openwrt-linux-musl-gcc" INSTALL_HDR_PATH=/workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/user_headers headers_install
grep '=[ym]' /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.config.set | LC_ALL=C sort | mkhash md5 > /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.vermagic
touch /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.configured
rm -f /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/init
make -C /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl=target-aarch64_cortex-a53+neon_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Fri Jul 29 12:37:10 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/workdir/openwrt/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.33 CC="aarch64-openwrt-linux-musl-gcc" Image.gz dtbs
make[5]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33'
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33'
cmp -s /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/vmlinux /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/vmlinux.debug || { aarch64-openwrt-linux-musl-objcopy -O binary -R .reginfo -R .notes -R .note -R .comment -R .mdebug -R .note.gnu.build-id -S /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/vmlinux /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/vmlinux; aarch64-openwrt-linux-musl-objcopy -R .reginfo -R .notes -R .note -R .comment -R .mdebug -R .note.gnu.build-id -S /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/vmlinux /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/vmlinux.elf; cp -fpR /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/vmlinux /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/vmlinux.debug;  cp -fpR /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/arch/arm64/boot//Image.gz /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/Image.gz;  }
touch /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/linux-5.10.33/.image
make -C image compile install TARGET_BUILD=
make[5]: Entering directory '/workdir/openwrt/target/linux/msm89xx/image'
make[5]: Nothing to be done for 'compile'.
mkdir -p /workdir/openwrt/bin/targets/msm89xx/msm8916 /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/tmp
rm -rf /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/json_info_files
/workdir/openwrt/staging_dir/host/bin/make_ext4fs -L rootfs -l 109051904 -b 4096 -m 0 -J -T 1659098230 /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/root.ext4 /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/root-msm89xx/
error: ext4_allocate_best_fit_partial: failed to allocate 191 blocks, out of space?
Creating filesystem with parameters:
    Size: 109051904
make[5]: *** [/workdir/openwrt/include/image.mk:334: /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/linux-msm89xx_msm8916/root.ext4] Error 1
make[4]: *** [Makefile:31: install] Error 2
make[3]: *** [Makefile:11: install] Error 2
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 6656
    Inode size: 256
    Journal blocks: 0
    Label: rootfs
    Blocks: 26624
    Block groups: 1
    Reserved blocks: 0
    Reserved block group size: 7
make[5]: Leaving directory '/workdir/openwrt/target/linux/msm89xx/image'
make[4]: Leaving directory '/workdir/openwrt/target/linux/msm89xx'
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/install#6.27#2.17#8.37
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/install] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:19: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53+neon_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by HandsomeYingyan** [comment]
@kaixin009 
去掉 dnsmasq就可以了
But that file is already provided by package * dnsmasq-full
@AK201314 
把ext4分区加大就能解决这个问题
error: ext4_allocate_best_fit_partial: failed to allocate 191 blocks, out of space?

**Comment by AK201314** [comment]
![image](https://user-images.githubusercontent.com/88940210/182008919-e40e5771-9ef9-4523-9315-059b7bc15890.png)
![image](https://user-images.githubusercontent.com/88940210/182008934-e5539f1b-cb5c-407b-af85-951fbf054719.png)
，大佬再帮看下这样合理么，撸的4g棒子，亮亮佬有阵子没更新了呢

**Comment by HandsomeYingyan** [comment]
104 -> 256
