### ISSUE TITLE
编译ok后默认英文语言，未集成中文，手动添加了luci-i18n！

### ISSUE THREAD

**Issue by AK201314** [HandsomeMod/HandsomeMod#11]
再次打扰大佬了，可否维护下源码默认中文首选呢，MSM8916火热玩棒中！！！

**Comment by gdzhujun** [comment]
Luci里面选中文，可以看看openwrt的编译，一样的

**Comment by AK201314** [comment]
大佬，有空多维护维护呗，
![01FE662B](https://user-images.githubusercontent.com/88940210/182025487-1ccd2bd5-4ca3-45e8-aac2-06cab257aa7f.png)
无线速率这块优化啥的，当做旁路由还是可以的，毕竟9.9包邮香呀！

**Comment by AK201314** [comment]
添加luci-i18n已ok！
