### ISSUE TITLE
首页概况能否加入温度显示呢，大佬。

### ISSUE THREAD

**Issue by AK201314** [HandsomeMod/HandsomeMod#12]
请求加入CPU温度显示代码呢

**Comment by slslll** [comment]
同求，对于UFI板子很方便，谢谢

**Comment by HandsomeYingyan** [comment]
由于某些原因，HandsomeMod项目在这个阶段不打算单独维护luci，有需要的话可以去上游项目openwrt的[luci](https://github.com/openwrt/luci)反映这个功能需求。
