### ISSUE TITLE
Feed back your work to official OpenWrt.org (supported devices)?

### ISSUE THREAD

**Issue by dreirund** [HandsomeMod/HandsomeMod#13]
Ahoj,

it seams to me that you added support for platforms that is not present in the official OpenWrt, e.g. the Qualcomm MSM89xx Family/ UFI 4G Router sticks (https://qust.me/post/msm8916/).

Great work, thanks!

To give back to the community, I suggest that you engage with openwrt.org so that your device supports can be added to mainline OpenWrt. Are you willing to do so?

This would also help long term device support, and people who want to use the latest OpenWrt (development) branch or for some other reasons need the official branch.

What exactly are your changes to upstream OpenWrt to get those devices supported you added support for? Do you have a standalone patch which includes only that?

Here is a forum thread about the MSM89xx based 4G WiFi routers in stick format: https://forum.openwrt.org/t/qualcomm-msm8916-lte-router-384mib-ram-2-4gib-flash-android-openwrt/131712/

Regards!

**Comment by HandsomeYingyan** [comment]
你好,

There is no such plan in short time.
Msm8916 support in HandsomeMod still in a early stage.
Some packages and kmods are not meet the quality required to enter mainline OpenWrt.
Userspace daemons related to modem depends on eudev which is conflict with some packages in OpenWrt.

In summary,There are lots of work to do before add msm89xx support to upstream OpenWrt.

Regards!
