### ISSUE TITLE
字母G无法被hidg0设备输出

### ISSUE THREAD

**Issue by bili-86196482** [HandsomeMod/HandsomeMod#14]
这是我的 gc -l:
ID 18d1:d001 'g1'
  UDC                   ci_hdrc.0
  bcdUSB                2.00
  bDeviceClass          0x00
  bDeviceSubClass       0x00
  bDeviceProtocol       0x00
  bMaxPacketSize0       64
  idVendor              0x18d1
  idProduct             0xd001
  bcdDevice             0.01
  Language:     0x409
    Manufacturer        HandsomeTech
    Product             HandsomeMod Device
    Serial Number       0123456789
  Function, type: ffs instance: adb
    dev_name            adb
  Function, type: hid instance: hid.1
    dev                 241:0
    protocol            1
    report_desc 5196a115719e029e7150251751958812951758813955751581912959129517539139567581502565571902965810c0
    report_length       8
    subclass            0
  Configuration: 'c1' ID: 1
    MaxPower            2
    bmAttributes        0x80
    Language:   0x409
      configuration     c1
    adb -> ffs adb
    hid.1 -> hid hid.1

这是我测试用的文件内容：
echo -ne '\x00\x00\x39\x00\x00\x00\x00\x00' > /dev/hidg0 #[CAPSLOCK]
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
sleep 0.1
echo -ne '\x00\x00\x0A\x00\x00\x00\x00\x00' > /dev/hidg0 #G
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
sleep 0.1
echo -ne '\x00\x00\x12\x00\x00\x00\x00\x00' > /dev/hidg0 #O
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
sleep 0.1
echo -ne '\x00\x00\x12\x00\x00\x00\x00\x00' > /dev/hidg0 #O
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
sleep 0.1
echo -ne '\x00\x00\x07\x00\x00\x00\x00\x00' > /dev/hidg0 #D
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
sleep 0.1
echo -ne '\x00\x00\x2C\x00\x00\x00\x00\x00' > /dev/hidg0 #[SPACE]
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
sleep 0.1
echo -ne '\x00\x00\x0F\x00\x00\x00\x00\x00' > /dev/hidg0 #L
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
sleep 0.1
echo -ne '\x00\x00\x18\x00\x00\x00\x00\x00' > /dev/hidg0 #U
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
sleep 0.1
echo -ne '\x00\x00\x06\x00\x00\x00\x00\x00' > /dev/hidg0 #C
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
sleep 0.1
echo -ne '\x00\x00\x0E\x00\x00\x00\x00\x00' > /dev/hidg0 #K
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0

这是文件（模拟HID设备）的输出:
OOD LUCK

在这之中，字母G无法被打印出来，请问我怎么可以解决这个问题？

**Comment by HandsomeYingyan** [comment]
这似乎不是与HandsomeMod或gc有关的问题，所以这个issue将会被关闭。gc只负责初始化gadget设备，你的hid能正常生成hidg0并输出部分字符就说明gc部分是没有问题的。问题或许出在你输入hidg0的数据中，查阅与hid gadget相关的文档应该不难解决这个问题。
