### ISSUE TITLE
缺少软件包

### ISSUE THREAD

**Issue by kkjoy** [HandsomeMod/HandsomeMod#20]
提示 kmod-nft-compat 不可用 无法找到相应内核的软件包 部分软件无法使用，
系统 HandsomeMod 21.03-Attila-SNAPSHOT r174-97512a1635 / LuCI openwrt-21.02 branch git-22.154.41894-1cf976c

**Comment by gdzhujun** [comment]
你是想用小猫咪吧？酷安看我的帖子

**Comment by kkjoy** [comment]
> 你是想用小猫咪吧？酷安看我的帖子

来个链接啊，很多软件都需要这个

**Comment by gdzhujun** [comment]
搜我用户名就能找到了

**Comment by kkjoy** [comment]
放弃了 直接搞了debian进去

**Comment by kkjoy** [comment]
原来是openwrt 2102的官方就没有这个包。
