### ISSUE TITLE
build fail for pinecube

### ISSUE THREAD

**Issue by juanesf** [HandsomeMod/HandsomeMod#3]
trying to create an image for pinecube fails to compile kmod-video-videobuf2 as missing videobuf2-dma-contig.ko

ERROR: module '/workdir/HandsomeMod/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/linux-5.4.111/drivers/media/common/videobuf2/videobuf2-dma-contig.ko' is missing.

modules/camera.mk:79: recipe for target '/workdir/HandsomeMod/bin/targets/sunxi/cortexa7/packages/kmod-video-videobuf2_5.4.111-1_arm_cortex-a7_neon-vfpv4.ipk' failed

LOG: https://github.com/juanesf/OpenWrt-PineCube/runs/2458895752?check_suite_focus=true

**Comment by HandsomeYingyan** [comment]
I recompile the pinecube target with default config,the kmod-video-videobuf2 generate with no problem on my own PC. Please check the **.config** file in your github action.

**Comment by juanesf** [comment]
confirmed when changing config.
try to compile with gstreamer-cedarx and there is error with glib2 without gstreamer working

https://github.com/juanesf/OpenWrt-PineCube/runs/2467720381?check_suite_focus=true
