### ISSUE TITLE
请求patch重构

### ISSUE THREAD

**Issue by zfdx123** [HandsomeMod/HandsomeMod#34]
内核不断更新，patch逐渐过时，在移植22.03过程中出现大量报错，在此请求各位大佬联合更新内核patch，适配更新的openwrt，我会在近期更新patch，并在此发布编译遇到的问题，请各位大佬，在此解答，谢谢，如果有大佬愿意一起做patch更新，那更好了

**Comment by Magical-Lin** [comment]
我觉得直接把设备移植提交到openwrt主线吧

**Comment by zfdx123** [comment]
> 我觉得直接把设备移植提交到openwrt主线吧

不是很懂arm的dts那部分怎么写，dts/qcom还是怎么样，都是patch形式存在，让我很困惑

**Comment by zfdx123** [comment]
看了一下应该是这样的目录结构msm89xx/file/arch/arm64/boot/dts/qcom,这样写可以干掉patch添加设备

**Comment by zfdx123** [comment]
![截图 2023-04-26 15-17-07](https://user-images.githubusercontent.com/47835976/234499230-977541d2-876e-455f-8c17-25d9fd27c84f.png)

修复了一些patch，进入内核编译阶段报错，等待大佬排查处理

**Comment by zfdx123** [comment]
已找到相关节点

**Comment by zfdx123** [comment]
[待测试](https://github.com/zfdx123/msm89xx-22.03/commit/e246a4adebb6f09c0563c0e8f467b83b33c03677)

**Comment by a520ass** [comment]
其实可以通过另一种方式启动最新的openwrt，就像amlogic-s9xxx-openwrt这个项目一样。直接用官方armvirt-64架构的openwrt rootfs，内核就用debian系统的，这样应该能解决openwrt wifi问题

**Comment by gdzhujun** [comment]
希望大佬们出手

hefeng ***@***.***>于2023年4月28日 周五09:22写道：

**Comment by zfdx123** [comment]
> 其实可以通过另一种方式启动最新的openwrt，就像amlogic-s9xxx-openwrt这个项目一样。直接用官方armvirt-64架构的openwrt rootfs，内核就用debian系统的，这样应该能解决openwrt wifi问题

在我主页有一个UFI-OpenWRT,是master但是还没有测试

**Comment by a520ass** [comment]
> > 其实可以通过另一种方式启动最新的openwrt，就像amlogic-s9xxx-openwrt这个项目一样。直接用官方armvirt-64架构的openwrt rootfs，内核就用debian系统的，这样应该能解决openwrt wifi问题
> 
> 在我主页有一个UFI-OpenWRT,是master但是还没有测试

可以编译一个，我的GitHub action云编译不行，不好调试

**Comment by zfdx123** [comment]
> 

您有时间的话帮我跑一下看看，我本地网络环境不太行，全看缘分

**Comment by a520ass** [comment]
不清楚WSL2的ubuntu能不能编译，先测试一下
![QQ截图20230428103025](https://user-images.githubusercontent.com/8427401/235040116-f46a8192-3d44-4af7-8358-2e8298cecb79.png)

**Comment by zfdx123** [comment]
> 不清楚WSL2的ubuntu能不能编译，先测试一下 ![QQ截图20230428103025](https://user-images.githubusercontent.com/8427401/235040116-f46a8192-3d44-4af7-8358-2e8298cecb79.png)

好的，感谢

**Comment by a520ass** [comment]
我用的github上的那个pr，已经编译出来了
![image](https://user-images.githubusercontent.com/8427401/235048004-9e34dee1-f3dc-4c1f-a783-1538cff0ba93.png)

**Comment by zfdx123** [comment]
> 我用的github上的那个pr，已经编译出来了 ![image](https://user-images.githubusercontent.com/8427401/235048004-9e34dee1-f3dc-4c1f-a783-1538cff0ba93.png)

那个pr用的patch添加设备树，目的是干掉patch

**Comment by a520ass** [comment]
已经正常启动了最新版本
![image](https://user-images.githubusercontent.com/8427401/235048753-d73a6eee-e427-4220-b3e1-3fa31725c682.png)

**Comment by zfdx123** [comment]
> 已经正常启动了最新版本 ![image](https://user-images.githubusercontent.com/8427401/235048753-d73a6eee-e427-4220-b3e1-3fa31725c682.png)

有时间测我这个fork吗，帮我看看，设备树我单独拿出来了

**Comment by zfdx123** [comment]
https://github.com/zfdx123/UFI-OpenWRT

**Comment by Magical-Lin** [comment]
> 已经正常启动了最新版本 ![image](https://user-images.githubusercontent.com/8427401/235048753-d73a6eee-e427-4220-b3e1-3fa31725c682.png)

wifi收发速率正常吗？是72mbps吗？

**Comment by a520ass** [comment]
wifi有点问题，作为客户端能扫描到路由器wifi，但连不上

**Comment by a520ass** [comment]
好像缺了包，我去安装一个

**Comment by a520ass** [comment]
已经弄好了，速度显示是正常
![QQ截图20230428131125](https://user-images.githubusercontent.com/8427401/235059820-afb12563-f3dc-4e96-b493-7256c08d78c5.png)

**Comment by gdzhujun** [comment]
> 已经弄好了，速度显示是正常
> ![QQ截图20230428131125](https://user-images.githubusercontent.com/8427401/235059820-afb12563-f3dc-4e96-b493-7256c08d78c5.png)

老哥用的哪个源码地址来一个

**Comment by a520ass** [comment]
就这个大佬提的pr啊   https://github.com/TravMurav/openwrt

**Comment by gdzhujun** [comment]
直接clone下来编译后Wi-Fi就是修好的吗？
hefeng ***@***.***>于2023年4月28日 周五14:22写道：

**Comment by a520ass** [comment]
内核都不同，不需要改什么WiFi的代码，测试了client模式WiFi正常

**Comment by gdzhujun** [comment]
> zfdx123
<img width="476" alt="截屏2023-04-28 18 52 14" src="https://user-images.githubusercontent.com/9395606/235130034-cf7d52c5-b1ac-44b8-a225-6231cb6cbf49.png">

<img width="476" alt="截屏2023-04-28 18 51 30" src="https://user-images.githubusercontent.com/9395606/235129987-c665f614-0fde-4f9d-a3f1-142ccbee1a0b.png">

大佬，
UFI-OpenWRT里选择不了目标平台啊

> 内核不断更新，patch逐渐过时，在移植22.03过程中出现大量报错，在此请求各位大佬联合更新内核patch，适配更新的openwrt，我会在近期更新patch，并在此发布编译遇到的问题，请各位大佬，在此解答，谢谢，如果有大佬愿意一起做patch更新，那更好了

**Comment by zfdx123** [comment]
> > zfdx123
> 
> <img alt="截屏2023-04-28 18 52 14" width="476" src="https://user-images.githubusercontent.com/9395606/235130034-cf7d52c5-b1ac-44b8-a225-6231cb6cbf49.png">
> 
> <img alt="截屏2023-04-28 18 51 30" width="476" src="https://user-images.githubusercontent.com/9395606/235129987-c665f614-0fde-4f9d-a3f1-142ccbee1a0b.png">
> 
> 大佬， UFI-OpenWRT里选择不了目标平台啊
> 
> > 内核不断更新，patch逐渐过时，在移植22.03过程中出现大量报错，在此请求各位大佬联合更新内核patch，适配更新的openwrt，我会在近期更新patch，并在此发布编译遇到的问题，请各位大佬，在此解答，谢谢，如果有大佬愿意一起做patch更新，那更好了

移步UFI-OpenWRT这个分支 22.03需要修改太多东西，而且22.03指定分支在5.10内核，放弃移植

**Comment by gdzhujun** [comment]
> 就这个大佬提的pr啊 https://github.com/TravMurav/openwrt

这个里面目标平台也没得选择啊？大佬是怎么编译出来的啊？

**Comment by a520ass** [comment]
> > 就这个大佬提的pr啊 https://github.com/TravMurav/openwrt
> 
> 这个里面目标平台也没得选择啊？大佬是怎么编译出来的啊？
我有编译好了的https://www.123pan.com/s/oPmuVv-Xccgh.html提取码:BZfe

**Comment by a520ass** [comment]
> > 就这个大佬提的pr啊 https://github.com/TravMurav/openwrt
> 
> 这个里面目标平台也没得选择啊？大佬是怎么编译出来的啊？

我有编译好了的https://www.123pan.com/s/oPmuVv-Xccgh.html提取码:BZfe

**Comment by aa889788** [comment]
> > > 就这个大佬提的pr啊 https://github.com/TravMurav/openwrt
> > 
> > 
> > 这个里面目标平台也没得选择啊？大佬是怎么编译出来的啊？
> 
> 我有编译好了的[https://www.123pan.com/s/oPmuVv-Xccgh.html提取码:BZfe](https://www.123pan.com/s/oPmuVv-Xccgh.html%E6%8F%90%E5%8F%96%E7%A0%81:BZfe)

你好，我用默认配置编译了之后，进系统用mmcli -m 0显示无modem,请问一下是需要额外选中什么模块吗？

**Comment by a520ass** [comment]
> > > > 就这个大佬提的pr啊 https://github.com/TravMurav/openwrt
> > > 
> > > 
> > > 这个里面目标平台也没得选择啊？大佬是怎么编译出来的啊？
> > 
> > 
> > 我有编译好了的[https://www.123pan.com/s/oPmuVv-Xccgh.html提取码:BZfe](https://www.123pan.com/s/oPmuVv-Xccgh.html%E6%8F%90%E5%8F%96%E7%A0%81:BZfe)
> 
> 你好，我用默认配置编译了之后，进系统用mmcli -m 0显示无modem,请问一下是需要额外选中什么模块吗？

不清楚，我不用modem，你可以问下那个国外的大佬，他好像能用modem，不过他是手机

**Comment by gdzhujun** [comment]
是不需要选目标平台吗？直接用默认的编译吗？

**Comment by zfdx123** [comment]
[OpenWRT-master](https://github.com/zfdx123/UFI-OpenWRT) 已开机，is关闭

**Comment by wackejohn** [comment]
哇哈哈哈。。。本人杂合了handsomemod和TravMurav的commit，并且hackl了netifd，开机需要重启network的问题也给解决了。。。
https://github.com/openwrt/openwrt/pull/11729#issuecomment-1631839517

**Comment by shangjiyu** [comment]
> 哇哈哈哈。。。本人杂合了handsomemod和TravMurav的commit，并且hackl了netifd，开机需要重启network的问题也给解决了。。。 [openwrt/openwrt#11729 (comment)](https://github.com/openwrt/openwrt/pull/11729#issuecomment-1631839517)

据TravMurav  Master 分支的 modemmanager 修复了这个问题

**Comment by wackejohn** [comment]
> 据TravMurav Master 分支的 modemmanager 修复了这个问题

啊这，有链接吗，这破问题，应该是netifd的问题。。。

**Comment by shangjiyu** [comment]
> > 据TravMurav Master 分支的 modemmanager 修复了这个问题
> 
> 啊这，有链接吗，这破问题，应该是netifd的问题。。。

https://github.com/openwrt/packages/pull/20304#issuecomment-1621046417

这个是不是解决了？

**Comment by wackejohn** [comment]
> 这个是不是解决了？

你应该没有测试过吧，我试过，对于qcom-soc内置的modem，无效。。。。ps: TravMurav 提交的commit，内置modem根本不能正常使用。。。。
