### ISSUE TITLE
Desktop on OpenWrt. Required packages for assembly?

### ISSUE THREAD

**Issue by WOWRT** [HandsomeMod/HandsomeMod#4]
Required packages for assembly on x86_64 PC?

**Comment by HandsomeYingyan** [comment]
Sorry for my bad English.
I don't really get your main idea.
Trying to answer it by guessing :p

* It don't need extra packages (compare to openwrt) for host envirenment while compile on x86 pc.
* I personally not recommanded use HandsomeMod as Desktop. It lacks lots of packages for daily use.

**Comment by WOWRT** [comment]
My English is not very good.  Sorry.
  I want to build OpenWrt with Desktop support.Which packages should I choose to build?

**Comment by HandsomeYingyan** [comment]
We support both wayland and xorg for now,but only tested on x86.
So you can chose openbox(on xorg) or weston(on wayland) for desktop environment.
kmod-drm* and kmod-hid* are also needed to run xorg or wayland.

This doesn't look like an issue.I guess we can close it.
