### ISSUE TITLE
error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"

### ISSUE THREAD

**Issue by jumbo77** [HandsomeMod/HandsomeMod#5]
-DCONF_KERNEL_VERSION_3_10 -DCONF_KERNEL_CMA -L/home/jumbo/HandsomeMod/staging_dir/toolchain-arm_arm926ej-s_gcc-8.4.0_musl_eabi/usr/lib -L/home/jumbo/HandsomeMod/staging_dir/toolchain-arm_arm926ej-s_gcc-8.4.0_musl_eabi/lib -znow -zrelro -I./include -c yuv_rotate.c -o yuv_rotate.c.o -fPIC -shared
In file included from yuv_rotate.c:13:
/home/jumbo/HandsomeMod/staging_dir/toolchain-arm_arm926ej-s_gcc-8.4.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/8.4.0/include/arm_neon.h:31:2: error: #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
 #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
  ^~~~~
Makefile:18: recipe for target 'yuv_rotate.c.o' failed
make[4]: *** [yuv_rotate.c.o] Error 1
make[4]: Leaving directory '/home/jumbo/HandsomeMod/build_dir/target-arm_arm926ej-s_musl_eabi/linux-sunxi_arm9/libuapi-1/src'
Makefile:148: recipe for target '/home/jumbo/HandsomeMod/build_dir/target-arm_arm926ej-s_musl_eabi/linux-sunxi_arm9/libuapi-1/.built' failed
make[3]: *** [/home/jumbo/HandsomeMod/build_dir/target-arm_arm926ej-s_musl_eabi/linux-sunxi_arm9/libuapi-1/.built] Error 2
make[3]: Leaving directory '/home/jumbo/HandsomeMod/feeds/handsomefeed/nonfree/allwinner/libuapi'
time: package/feeds/handsomefeed/libuapi/compile#0.09#0.00#0.11
    ERROR: package/feeds/handsomefeed/libuapi failed to build.
package/Makefile:114: recipe for target 'package/feeds/handsomefeed/libuapi/compile' failed
make[2]: *** [package/feeds/handsomefeed/libuapi/compile] Error 1
make[2]: Leaving directory '/home/jumbo/HandsomeMod'
package/Makefile:110: recipe for target '/home/jumbo/HandsomeMod/staging_dir/target-arm_arm926ej-s_musl_eabi/stamp/.package_compile' failed
make[1]: *** [/home/jumbo/HandsomeMod/staging_dir/target-arm_arm926ej-s_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jumbo/HandsomeMod'
/home/jumbo/HandsomeMod/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by HandsomeYingyan** [comment]
We don't provide any kind of support on cedarx.
If you have any issue please contact allwinner for help.
