### ISSUE TITLE
编译成功后需要如何安装到设备上呢？

### ISSUE THREAD

**Issue by gdzhujun** [HandsomeMod/HandsomeMod#6]
得到handsomemod-msm89xx-msm8916-Handsome_handsome-openstick-ufi001c-ext4-boot.img.gz和handsomemod-msm89xx-msm8916-Handsome_handsome-openstick-ufi001c-ext4-system.img.gz，需要如何刷到设备上呢？

**Comment by HandsomeYingyan** [comment]
解压后使用fastboot刷写到对应分区即可，system.img对应rootfs分区 具体参照openstick项目中的debian刷写脚本

**Comment by gdzhujun** [comment]
刷入之后无法正常启动 不清楚是否编译配置中有什么必选项没有选中

**Comment by gdzhujun** [comment]
不需要回安卓 插上电脑可以进fastboot模式直接刷

**Comment by kalagxw** [comment]
插上电脑如何进fastboot模式
