### ISSUE TITLE
大佬请问ufi003板子，编译时候选择哪项

### ISSUE THREAD

**Issue by slslll** [HandsomeMod/HandsomeMod#7]
![image](https://user-images.githubusercontent.com/38198381/174962879-1b7a699c-f95a-42e9-9289-7a1d4031eb65.png)

**Comment by HandsomeYingyan** [comment]
选UFI001C即可，需要在firmware选项中勾选UFI003相关的firmware并取消掉UFI001C的firmware。

**Comment by slslll** [comment]
明白了，谢谢

> 选UFI001C即可，需要在firmware选项中勾选UFI003相关的firmware并取消掉UFI001C的firmware。
