### ISSUE TITLE
请问源码有集成wcn36xx: Fix HT40 capability for 2Ghz band的PATCH吗？

### ISSUE THREAD

**Issue by gdzhujun** [HandsomeMod/HandsomeMod#8]
请问大佬有集成http://lists.infradead.org/pipermail/wcn36xx/2021-October/002580.html 这个补丁吗？

**Comment by HandsomeYingyan** [comment]
目前没有，考虑未来整合5.15的无线驱动以后再加入这个patch

**Comment by HandsomeYingyan** [comment]
目前的版本中已经包含这个patch，linux-backport项目在5.15加入了这个patch
