### ISSUE TITLE
希望可以为UFI板子添加cpufreq支持，让其可以调整cpu频率

### ISSUE THREAD

**Issue by slslll** [HandsomeMod/HandsomeMod#9]
相关知识不了解，不知是否方便实现，谢谢作者

**Comment by HandsomeYingyan** [comment]
内核驱动是支持cpufreq的，应该安装相应的luci插件就能进行管理了。

**Comment by HandsomeYingyan** [comment]
内核驱动是支持cpufreq的，应该安装相应的luci插件就能进行管理了。

**Comment by slslll** [comment]
> 内核驱动是支持cpufreq的，应该安装相应的luci插件就能进行管理了。

明白了，谢谢
